// Generated by data/equipmentscrapper.js — do not edit by hand.
// Per-category, per-tier gear stat bonuses from
// https://schaledb.com/data/en/equipment.min.json — statValue is the maxed
// StatValue[i][1] SchaleDB applies; statType keeps the _Base/_Coefficient
// suffix that decides how it combines (see utils/statCalc.ts combineStat).
export interface EquipmentTierStats {
  statType: string[];
  statValue: number[];
}

export const EQUIPMENT_MAX_TIER = 10;

// Index by [category][tier - 1]; tier 0 = nothing equipped.
export const equipmentStats: Record<string, EquipmentTierStats[]> = {
  Hat: [
    { statType: ["AttackPower_Coefficient"], statValue: [800] },
    { statType: ["AttackPower_Coefficient"], statValue: [1300] },
    { statType: ["AttackPower_Coefficient"], statValue: [1800] },
    { statType: ["AttackPower_Coefficient","CriticalDamageRate_Base"], statValue: [2500,800] },
    { statType: ["AttackPower_Coefficient","CriticalDamageRate_Base"], statValue: [3000,1200] },
    { statType: ["AttackPower_Coefficient","CriticalDamageRate_Base"], statValue: [3500,1600] },
    { statType: ["AttackPower_Coefficient","CriticalDamageRate_Base"], statValue: [4000,1800] },
    { statType: ["AttackPower_Coefficient","CriticalDamageRate_Base"], statValue: [4500,2000] },
    { statType: ["AttackPower_Coefficient","CriticalDamageRate_Base"], statValue: [4800,2000] },
    { statType: ["AttackPower_Coefficient","CriticalDamageRate_Base"], statValue: [5000,2000] },
  ],
  Gloves: [
    { statType: ["AttackPower_Coefficient"], statValue: [640] },
    { statType: ["AttackPower_Coefficient"], statValue: [1040] },
    { statType: ["AttackPower_Coefficient"], statValue: [1440] },
    { statType: ["AttackPower_Coefficient","CriticalPoint_Base"], statValue: [2000,70] },
    { statType: ["AttackPower_Coefficient","CriticalPoint_Base"], statValue: [2500,200] },
    { statType: ["AttackPower_Coefficient","CriticalPoint_Base","AccuracyPoint_Base"], statValue: [3000,300,30] },
    { statType: ["AttackPower_Coefficient","CriticalPoint_Base","AccuracyPoint_Base"], statValue: [3500,350,200] },
    { statType: ["AttackPower_Coefficient","CriticalPoint_Base","AccuracyPoint_Base"], statValue: [4000,370,220] },
    { statType: ["AttackPower_Coefficient","CriticalPoint_Base","AccuracyPoint_Base"], statValue: [4600,450,220] },
    { statType: ["AttackPower_Coefficient","CriticalPoint_Base","AccuracyPoint_Base"], statValue: [5000,500,220] },
  ],
  Shoes: [
    { statType: ["AttackPower_Coefficient"], statValue: [400] },
    { statType: ["AttackPower_Coefficient"], statValue: [650] },
    { statType: ["AttackPower_Coefficient"], statValue: [900] },
    { statType: ["AttackPower_Coefficient","MaxHP_Coefficient"], statValue: [1250,600] },
    { statType: ["AttackPower_Coefficient","MaxHP_Coefficient"], statValue: [2000,900] },
    { statType: ["AttackPower_Coefficient","MaxHP_Coefficient"], statValue: [2500,1200] },
    { statType: ["AttackPower_Coefficient","MaxHP_Coefficient"], statValue: [3000,1350] },
    { statType: ["AttackPower_Coefficient","MaxHP_Coefficient"], statValue: [3500,1500] },
    { statType: ["AttackPower_Coefficient","MaxHP_Coefficient"], statValue: [4200,1750] },
    { statType: ["AttackPower_Coefficient","MaxHP_Coefficient"], statValue: [4600,2000] },
  ],
  Bag: [
    { statType: ["MaxHP_Base"], statValue: [600] },
    { statType: ["MaxHP_Base"], statValue: [975] },
    { statType: ["MaxHP_Base"], statValue: [1350] },
    { statType: ["MaxHP_Base","DefensePower_Base"], statValue: [1875,1000] },
    { statType: ["MaxHP_Base","DefensePower_Base"], statValue: [3500,1100] },
    { statType: ["MaxHP_Base","DefensePower_Base"], statValue: [5500,1200] },
    { statType: ["MaxHP_Base","DefensePower_Base"], statValue: [7500,1300] },
    { statType: ["MaxHP_Base","DefensePower_Base"], statValue: [9500,1400] },
    { statType: ["MaxHP_Base","DefensePower_Base","MaxHP_Coefficient"], statValue: [12000,1600,500] },
    { statType: ["MaxHP_Base","DefensePower_Base","MaxHP_Coefficient"], statValue: [14000,1700,500] },
  ],
  Badge: [
    { statType: ["MaxHP_Base"], statValue: [800] },
    { statType: ["MaxHP_Base"], statValue: [1300] },
    { statType: ["MaxHP_Base"], statValue: [1800] },
    { statType: ["MaxHP_Base","HealEffectivenessRate_Base"], statValue: [2500,1000] },
    { statType: ["MaxHP_Base","HealEffectivenessRate_Base","MaxHP_Coefficient"], statValue: [4500,2000,1000] },
    { statType: ["MaxHP_Base","HealEffectivenessRate_Base","MaxHP_Coefficient"], statValue: [6500,3000,1800] },
    { statType: ["MaxHP_Base","HealEffectivenessRate_Base","MaxHP_Coefficient","DodgePoint_Base"], statValue: [9500,3200,2200,400] },
    { statType: ["MaxHP_Base","HealEffectivenessRate_Base","MaxHP_Coefficient","DodgePoint_Base"], statValue: [12000,3400,2400,450] },
    { statType: ["MaxHP_Base","HealEffectivenessRate_Base","MaxHP_Coefficient","DodgePoint_Base"], statValue: [14000,3500,2500,450] },
    { statType: ["MaxHP_Base","HealEffectivenessRate_Base","MaxHP_Coefficient","DodgePoint_Base"], statValue: [16000,3500,2500,450] },
  ],
  Hairpin: [
    { statType: ["MaxHP_Base"], statValue: [400] },
    { statType: ["MaxHP_Base"], statValue: [650] },
    { statType: ["MaxHP_Base"], statValue: [900] },
    { statType: ["MaxHP_Base","OppressionResist_Coefficient"], statValue: [1250,1000] },
    { statType: ["MaxHP_Base","OppressionResist_Coefficient"], statValue: [3000,2000] },
    { statType: ["MaxHP_Base","OppressionResist_Coefficient"], statValue: [4500,2400] },
    { statType: ["MaxHP_Base","OppressionResist_Coefficient"], statValue: [6500,2800] },
    { statType: ["MaxHP_Base","OppressionResist_Coefficient"], statValue: [8500,3200] },
    { statType: ["MaxHP_Base","OppressionResist_Coefficient","CriticalPoint_Base"], statValue: [11000,3400,150] },
    { statType: ["MaxHP_Base","OppressionResist_Coefficient","CriticalPoint_Base"], statValue: [13000,3600,150] },
  ],
  Charm: [
    { statType: ["CriticalChanceResistPoint_Base"], statValue: [80] },
    { statType: ["CriticalChanceResistPoint_Base"], statValue: [130] },
    { statType: ["CriticalChanceResistPoint_Base"], statValue: [180] },
    { statType: ["CriticalChanceResistPoint_Base","CriticalDamageResistRate_Base"], statValue: [250,1000] },
    { statType: ["CriticalChanceResistPoint_Base","CriticalDamageResistRate_Base","CriticalPoint_Base"], statValue: [280,1500,120] },
    { statType: ["CriticalChanceResistPoint_Base","CriticalDamageResistRate_Base","CriticalPoint_Base"], statValue: [320,1800,150] },
    { statType: ["CriticalChanceResistPoint_Base","CriticalDamageResistRate_Base","CriticalPoint_Base"], statValue: [360,2100,180] },
    { statType: ["CriticalChanceResistPoint_Base","CriticalDamageResistRate_Base","CriticalPoint_Base"], statValue: [380,2400,200] },
    { statType: ["CriticalChanceResistPoint_Base","CriticalDamageResistRate_Base","CriticalPoint_Base"], statValue: [400,2700,250] },
    { statType: ["CriticalChanceResistPoint_Base","CriticalDamageResistRate_Base","CriticalPoint_Base"], statValue: [420,3000,300] },
  ],
  Watch: [
    { statType: ["CriticalPoint_Base"], statValue: [80] },
    { statType: ["CriticalPoint_Base"], statValue: [130] },
    { statType: ["CriticalPoint_Base"], statValue: [180] },
    { statType: ["CriticalPoint_Base","CriticalDamageRate_Base"], statValue: [250,1000] },
    { statType: ["CriticalPoint_Base","CriticalDamageRate_Base","MaxHP_Coefficient"], statValue: [280,1500,500] },
    { statType: ["CriticalPoint_Base","CriticalDamageRate_Base","MaxHP_Coefficient"], statValue: [320,1800,700] },
    { statType: ["CriticalPoint_Base","CriticalDamageRate_Base","MaxHP_Coefficient"], statValue: [360,2100,900] },
    { statType: ["CriticalPoint_Base","CriticalDamageRate_Base","MaxHP_Coefficient"], statValue: [400,2400,1100] },
    { statType: ["CriticalPoint_Base","CriticalDamageRate_Base","MaxHP_Coefficient"], statValue: [440,2500,1300] },
    { statType: ["CriticalPoint_Base","CriticalDamageRate_Base","MaxHP_Coefficient"], statValue: [480,2600,1500] },
  ],
  Necklace: [
    { statType: ["HealPower_Coefficient","OppressionPower_Coefficient"], statValue: [800,800] },
    { statType: ["HealPower_Coefficient","OppressionPower_Coefficient"], statValue: [1300,1300] },
    { statType: ["HealPower_Coefficient","OppressionPower_Coefficient"], statValue: [1800,1800] },
    { statType: ["HealPower_Coefficient","OppressionPower_Coefficient"], statValue: [2500,2500] },
    { statType: ["HealPower_Coefficient","OppressionPower_Coefficient","AttackPower_Coefficient"], statValue: [2800,2800,400] },
    { statType: ["HealPower_Coefficient","OppressionPower_Coefficient","AttackPower_Coefficient"], statValue: [3200,3200,600] },
    { statType: ["HealPower_Coefficient","OppressionPower_Coefficient","AttackPower_Coefficient"], statValue: [3500,3500,800] },
    { statType: ["HealPower_Coefficient","OppressionPower_Coefficient","AttackPower_Coefficient"], statValue: [3800,3800,1000] },
    { statType: ["HealPower_Coefficient","OppressionPower_Coefficient","AttackPower_Coefficient"], statValue: [4000,3800,1400] },
    { statType: ["HealPower_Coefficient","OppressionPower_Coefficient","AttackPower_Coefficient"], statValue: [4200,3800,1800] },
  ],
};
