// Generated by data/expscrapper.js — do not edit by hand.
// Level EXP tables from github.com/electricgoat/ba-data (global branch);
// report values and credit price cross-checked against
// bluearchive.wiki/wiki/Character_Exp_table.

export const STUDENT_EXP_MAX_LEVEL = 90;

// EXP needed to go from level (index + 1) to (index + 2); 0 at the cap.
export const STUDENT_EXP_TO_NEXT: number[] = [
  10, 25, 40, 55, 70, 75, 80, 90, 95, 105,
  115, 130, 145, 160, 175, 185, 200, 215, 230, 385,
  425, 480, 535, 580, 635, 785, 845, 895, 925, 975,
  1010, 1095, 1165, 1250, 1335, 1425, 1545, 1625, 1685, 1735,
  1800, 1975, 2165, 2370, 2585, 2815, 3065, 3340, 3645, 3985,
  4365, 4790, 5265, 5795, 6385, 7040, 7765, 8565, 9445, 10410,
  11465, 12615, 13865, 15220, 16685, 18265, 19965, 21790, 23745, 25700,
  27655, 29610, 31565, 33520, 35475, 37430, 39385, 39385, 39385, 39385,
  39385, 39385, 39385, 43295, 52265, 69200, 84420, 102990, 125645, 0,
];

export const ACCOUNT_EXP_MAX_LEVEL = 90;

export const ACCOUNT_EXP_TO_NEXT: number[] = [
  8, 10, 15, 21, 28, 36, 45, 55, 66, 79,
  93, 108, 124, 141, 159, 178, 198, 219, 241, 265,
  288, 312, 337, 363, 390, 418, 447, 477, 508, 581,
  656, 734, 814, 897, 982, 1069, 1159, 1251, 1346, 1443,
  1543, 1645, 1750, 1857, 1966, 2078, 2192, 2309, 2428, 2550,
  2674, 2800, 2929, 3060, 3194, 3330, 3469, 3610, 3754, 3900,
  4048, 4199, 4352, 4508, 4666, 4831, 5007, 5186, 5369, 5556,
  5747, 5942, 6141, 6344, 6552, 6768, 6989, 7216, 7449, 7682,
  7915, 8148, 8381, 8883, 9460, 10614, 12922, 17538, 26770, 0,
];

// Activity reports: EXP granted per report tier.
export const EXP_REPORTS: { label: string; exp: number }[] = [
  { label: 'Superior Activity Report', exp: 10000 },
  { label: 'Advanced Activity Report', exp: 2000 },
  { label: 'Normal Activity Report', exp: 500 },
  { label: 'Novice Activity Report', exp: 50 },
];

// Applying student EXP costs 7 credits per EXP point.
export const CREDITS_PER_EXP = 7;
