// Shape of data/banners.json, generated by data/bannerscrapper.js from the
// Blue Archive wiki banner lists. All timestamps are unix milliseconds.

export interface BannerStudent {
  /** SchaleDB student id; null when the wiki name couldn't be resolved. */
  id: number | null;
  name: string;
}

export interface BannerWindow {
  start: number;
  end: number;
}

// PickupGacha | LimitedGacha | FesGacha | SelectPickupGacha |
// SelectPickupLimitedGacha | SelectPickupFesGacha — kept open for new types.
export type BannerType = string;

export interface Banner {
  /** Wiki banner code, e.g. "Rio_(Battle)_release" — unique per run. */
  code: string;
  type: BannerType;
  rerun: boolean;
  students: BannerStudent[];
  /** JP run window; null for Global-exclusive runs. */
  jp: BannerWindow | null;
  /** Confirmed Global run window; null if it hasn't run on Global. */
  global: BannerWindow | null;
  /** JP window shifted by the current JP→Global offset; set only when `global` is null. */
  predictedGlobal: BannerWindow | null;
}

export interface BannerData {
  generatedAt: number;
  /** JP→Global schedule offset (median of recent matched runs), in days. */
  offsetDays: number;
  banners: Banner[];
}
